statements:
  - Effect: Allow
    Action:
      - dynamodb:PutItem
      - dynamodb:GetItem
      - dynamodb:UpdateItem
      - dynamodb:Query
    Resource:
      - !GetAtt MainTable.Arn
      - !Sub "${MainTable.Arn}/index/*"
  - Effect: Allow
    Action:
      - cognito-idp:AdminDeleteUser
    Resource:
      - !GetAtt UserPool.Arn
  - Effect: Allow
    Action:
      - s3:PutObject
      - s3:GetObject
      - s3:DeleteObject
    Resource: !Sub "${MealsBucket.Arn}/*"
  - Effect: Allow
    Action:
      - sqs:SendMessage
    Resource: !GetAtt MealsQueue.Arn
